Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using First.Repo.Contract;
using First.Models.ViewModel;
using First.DATABASE;
using First.Models;

namespace First.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee EmployeeService;
        private readonly Databasefile _Conn;
        public EmployeeController(IEmployee employee, Databasefile Conn) { EmployeeService = employee; _Conn = Conn; }
        public IActionResult Index()
        { 

            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateEmployee(EmployeeViewModel model)
        {

            var result = EmployeeService.CreateEmployee(model);
            return RedirectToAction("Index");
        }
        public IActionResult GetEmployee()
        {
            var Query = (from E in _Conn.Employees
                         join Q in _Conn.Qualifications on E.Qf.Id equals Q.Id
                         join C in _Conn.Countries on E.Country.C_Id equals C.C_Id
                         join S in _Conn.States on E.State.S_Id equals S.S_Id
                         select new EmployeeViewModel
                         {
                             Id = E.Id,
                             Name = E.Name,
                             Gender = E.Gender,
                             QualificationName = Q.Name,
                             Address = E.Address,
                             CountryName = C.CountryName,
                             StateName = S.StateName,
                             IsActive = E.IsActive
                         }).ToList();
            return Json(Query);
        }
        public IActionResult GetQualifications()
        {
            var quali = EmployeeService.GetQualifications();
            return Json(quali);
        }
        public IActionResult GetCountry()
        {
            var quali1 = EmployeeService.GetCountry();
            return Json(quali1);
        }
        public IActionResult GetState(int id)
        {
            var statebind = _Conn.States.Where(x => x.GetCountry.C_Id == id).ToList();
            return Json(statebind);
        }
        [HttpPost]
        public IActionResult DeleteEmployee(int id)
        {
            var result = EmployeeService.DeleteEmployee(id);
            //return Json(emp);

            if (result)
            {
                return Json(new { ok = true, message = "Employee Deleted Successfully.." });
            }
            else
            {
                return Json(new { ok = false, message = "Employee Not Found.." });
            }
        }

        //public IActionResult UpdateEmployee()
        //{
        //    return View();
        //}

        //[HttpGet]
        //public IActionResult GetEmployeeById(int id)
        //{
        //    var emp1 = EmployeeService.GetEmployeeById(id);
        //    return RedirectToAction("UpdateEmployee",emp1);
        //}

        [HttpGet]
        public IActionResult UpdateEmployee(int id)
        {
            var empDetails = EmployeeService.GetEmployeeById(id);
            var empModel = new EmployeeViewModel();
            empModel.Id = empDetails.Id;
            empModel.Name = empDetails.Name;
            empModel.Gender = empDetails.Gender;
            empModel.Address = empDetails.Address;
          //  empModel.QualificationName = empDetails.Qf.Name;
           // empModel.CountryName = empDetails.Country.CountryName;
          //  empModel.StateName = empDetails.State.StateName;
            empModel.IsActive = empDetails.IsActive;
            return View(empModel);
        }

        [HttpPost]
        public IActionResult UpdateEmployee(EmployeeViewModel model)
        {
            var result = EmployeeService.UpdateEmployee(model);

            if (result != null)
            {
                return RedirectToAction("Index");
            }
            else
            {

                return Json(new { ok = false, message = "Somthing Went Wrong..." });
            }
        }
    }
}

Controllers/StrudentApiCallController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using First.API.Models;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;

namespace First.Controllers
{
    public class StrudentApiCallController : Controller
    {
        public async Task<IActionResult> Index()
        {
            List<Student> students = new List<Student>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://localhost:44326/api/Student/GetStudents"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    students = JsonConvert.DeserializeObject<List<Student>>(apiResponse);
                }
            }
                return View(students);
        }

        //[HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Student students)
        {
            Student lstudents = new Student();
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(students), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("https://localhost:44326/api/Student/CreateStudent", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    lstudents = JsonConvert.DeserializeObject<Student>(apiResponse);
                }
            }
            return RedirectToAction("Index");

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - First</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
    @*<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet" />*@


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">First</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">EmployeeDetails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewEmployee" asp-action="Index"> New Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StrudentApiCall" asp-action="Index"> StudentApiView</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - First - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>